homework 1
MAK-Cpp/backend-java-s1 pull request #1
Opened 2023-10-03 17:35 UTC by MAK-Cpp

2023-10-05 06:49 UTC, nexen505 requested changes
Отличная работа. Замечания в основном косметические.

2023-10-05 06:49 UTC, nexen505 commented on src/test/java/edu/hw1/HomeworkTasksTest.java
> +public class HomeworkTasksTest {
Проблема: тест плохо воспринимается из-за объединения разнородных тестов и со временем будет разрастаться.

Предложение: разбить тесты отдельных задач по отдельным файлам в духе `Task0Test.java`, `Task1Test.java` и т.д.

2023-10-05 06:49 UTC, nexen505 commented on src/test/java/edu/hw1/HomeworkTasksTest.java
> +        assertEquals(60, Task1.minutesToSeconds("01:00"));
Предложение: здесь и в других тестах можно воспользоваться механизмом параметризованных тестов (https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests). Например, данный тест разбивается на два отдельных параметризованных: на корректных и некорректных входных данных. Примерно это так может выглядеть:

```java
@ParameterizedTest
@MethodSource("validArgs")
void shouldCalculateSeconds(String input, int expectedResult) {
    assertEquals(expectedResult, Task1.minutesToSeconds(input));
}

private static Stream<Arguments> validArgs() {
    return Stream.of(Arguments.of("13:56", 836), Arguments.of("01:00", 60));
}

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task0.java
> +    public static void printHelloWorld() {
Предложение: добавить тест на проверку вывода в `System.out` с использованием, например, https://github.com/stefanbirkner/system-lambda#systemout-and-systemerr

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task1.java
> +                    isException = true;
Косметика: в целом, тут и в других подобных ситуациях можно сразу делать `return -1;`, это упростит восприятие и понимание.

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task1.java
> +                    if (seconds >= COUNT_SECONDS_IN_MINUTE) {
Предложение: добавить тест на такой случай.

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task2.java
> +        int integerToParse = integer;
Косметика: в целом, это можно в объявление циклов перенести. В этом не будет "неприемлемого дублирования".

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task0.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Косметика: здесь и в других классах порядок не соответствует спецификации

```java suggestion
    private static final Logger LOGGER = LogManager.getLogger();
```

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task4.java
> +        StringBuilder builderFixedString = new StringBuilder();
Проблема: без указания размера тут могут происходить лишние копирования внутреннего массива при манипуляциях.

Предложение: указать известный размер, чтобы оптимально использовать память.

```java suggestion
        StringBuilder builderFixedString = new StringBuilder(brokenString.length());
```

2023-10-05 06:49 UTC, nexen505 commented on src/main/java/edu/hw1/tasks/Task5.java
> +        for (anotherNumber = number; anotherNumber >= NUMBER_SYSTEM && !isPalindrome(anotherNumber);
Проблема: насколько понимаю, в случае палиндрома не менее десяти функция `isPalindrome` вызовется дважды, что избыточно.

Предложение: сначала проверить палиндром единожды.

2023-10-05 07:04 UTC, MAK-Cpp commented on src/main/java/edu/hw1/tasks/Task1.java
> +                    isException = true;
Там везде изначально были `return -1;`, но checkstyle ругался на большое кол-во ретурнов, пришлось костыли писать

2023-10-05 13:58 UTC, nexen505 approved these changes
👍

2023-10-06 05:24 UTC, nexen505 approved these changes

2023-10-06 07:11 UTC, nexen505 approved these changes

2023-10-06 07:12 UTC, nexen505 approved these changes

2023-10-06 07:17 UTC, merged