Hw9
MAK-Cpp/backend-java-s1 pull request #11
Opened 2023-12-07 23:38 UTC by MAK-Cpp

2023-12-08 11:22 UTC, nexen505 requested changes

2023-12-08 11:22 UTC, nexen505 commented on src/main/java/edu/hw9/tasks/task1/MultiThreadStatsCollector.java
> +                averages.get(name).value(),
Проблема: возможна гонка на ключах, так как они в разные мапы добавляются параллельно.

Предложение: реализовать одну мапу с объектами, которые содержат все показатели.

2023-12-08 11:22 UTC, nexen505 commented on src/main/java/edu/hw9/tasks/task2/RecursiveSearchBigFolders.java
> +            return ForkJoinTask.invokeAll(pathStream.map(RecursiveSearchBigFolders::new).toList()).stream()
Это относится и к соседней реализации задания.

Проблема: вся эта конструкция очень плохо читается.

Предложение: разбить на отдельные переменные и вызовы.

2023-12-08 11:22 UTC, nexen505 commented on src/main/java/edu/hw9/tasks/task3/MultiThreadDFS.java
> +public class MultiThreadDFS {
Проблема: тут реализовано нечто иное, чем поиск в глубину.

Предложение: реализовать поиск пути в ориентированном графе через параллельный поиск в глубину.

2023-12-08 11:45 UTC, MAK-Cpp commented on src/main/java/edu/hw9/tasks/task3/MultiThreadDFS.java
> +public class MultiThreadDFS {
Это реализация алгоритма поиска всех компонент связанности в неоирентированном графе через дфс, в ТЗ сказано реализовать **какой-то** алгоритм поиска в глубину без объяснения его цели, поэтому пришлось придумать задачу, в которой поиск в глубину помогает в решении, и написать для нее соответствующий алгоритм, я реализую предложенный вами алгоритм, но мне кажется данный кейс хорошо показывает проблему неполного ТЗ

2023-12-18 12:25 UTC, nexen505 requested changes

2023-12-18 12:25 UTC, nexen505 commented on src/main/java/edu/hw9/tasks/task1/MultiThreadStatsCollector.java
> +            stats.merge(statName, toMerge, Statistic::merge);
Проблема: метод `Statistic::merge` непотокобезопасен из-за мутабельности, что делает опасным его использование в `ConcurrentMap#merge` и эту проблему сложно отловить.

Предложение: сделать, чтобы `Statistic::merge` возвращал новый объект, а не мутировал имеющийся.

2023-12-18 12:25 UTC, nexen505 commented on src/test/java/edu/hw9/tasks/task1/MultiThreadStatsCollectorTest.java
> +                    List<Entry<String, double[]>> tasks = inputs.get(id.getAndIncrement());
Косметика: использование внешнего идентификатора можно заменить на создание и использование `IntStream#range`.

2023-12-19 11:16 UTC, nexen505 approved these changes

2023-12-19 11:23 UTC, merged